### ISSUE TITLE
Keeps switching to Source in Chrome

### ISSUE THREAD

**Issue by ironhide1975** [MisterPhilip/omnibug#160]
**Describe the bug**
Not sure if this is an issue with Omnibug or Chrome, but for some reason on this one site I'm working on the page initially loads, if I have Omnibug open, it then suddenly switches to the source tab in the Developer panel. I have to click back to Omnibug then.

**To Reproduce**
Load a page with Omnibug open.

**Expected behavior**
Omnibug should stay open

**Desktop (please complete the following information):**
Windows

**Additional context**

**Comment by MisterPhilip** [comment]
What version of Chrome are you on and does this happen with all sites or just specific ones?

**Comment by ironhide1975** [comment]
Version 96. 0.4664.110
It just does this for this one site so far. I need to test it on a few other sites. I checked and I didn't have any breakpoints set either. Once again not sure if its a Chrome issue or something else.

**Comment by johndavidsimmons** [comment]
This happens to me too, but only on some sites. I always thought it was Chrome...

**Comment by MisterPhilip** [comment]
Interesting, I haven't seen it do this yet. If you have a site that you can replicate it in please let me know (either here or philip@omnibug.io) and I'll see whats up!

**Comment by MisterPhilip** [comment]
I'm closing this since I don't think it is Omnibug specific. When testing out the Glassbox additions I was able to replicate it from any of the default devtools tabs (network, memory, etc.) when loading www.glassbox.com. The brief time it showed code, it pointed to a `debugger` statement, but I'm not sure why it didn't do a full breakpoint.
