### ISSUE TITLE
Decision if url to be parsed based on URL AND postData

### ISSUE THREAD

**Issue by nikelone** [MisterPhilip/omnibug#179]
**Is your feature request related to a problem? Please describe.**
Jentis tracking platform uses a first party tracking, without any url parameter and a custom subdomain. See for example here: https://www.jentis.com/. Look out for the post requests with a huge base64 encoded body.

**Describe the solution you'd like**
I would like to add jentis as provider, but due to how jentis is sending the data it is only possible, if we do not evaluate the URL only but also the post body.

**Describe alternatives you've considered**
I couldn't come up with some.

**Additional context**
I think in the future this feature might get more relevant for more tracking provider, as there is a movement towards own and custom tracking protocols and  using tracking proxy, e.g. google server side tagmanager.

**Comment by MisterPhilip** [comment]
Unfortunately, I don't think this is possible without capturing every URL and then examining the body (and in this case, base64 decoding it) - which would be very resource expensive. Even with the newer `declarativeNetRequests`, you can only view the URL and not the POST data sent with it. The only other way around this I see is to add a listener on the page for the `jentis` object (or similar), but currently I have no plans to add any page-level listeners due to the added complexity & overhead. If there is a better way to do this in the future, I'd definitely like to give it a try!

**Comment by nikelone** [comment]
Hi, I understand. This is what I assumed. But thanks a lot for taking the time answering my request and for developing this very nice and helpful tool!
