### ISSUE TITLE
Every Piwik PRO-event is tracked as pageview in Omnibug

### ISSUE THREAD

**Issue by Thorsager84** [MisterPhilip/omnibug#214]
**Describe the bug**
Hi. I'm having an issue where all events are shown as pageviews. It seems to be specific to Piwik PRO and not other analytics products

**To Reproduce**
1. Open chrome (version 111.0.5563.65)
2. Go to a webpage, fx https://businessindenmark.virk.dk/.
3. Use diffirent navigational patterns, links and searches
4. In the network-pane, take note of the Piwik event-type (action, ping, click).
5. Every Piwik tracking event is registreret as a pageview, including pings.

**Expected behavior**
I expect every event to be shown as expected in the omnibug-pane

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 111
 - Omnibug Version v1.20.0

**Additional context**
As seen in the network-panel, Piwik PRO is sending the correct data. This issue is purely an omnibug-thing. It works in Firefox as well.

**Comment by MisterPhilip** [comment]
Sorry I missed this! It's been quite a busy year on my side. 

It looks like this is because of #213  - for whatever reason Chromium decided to not expose the POST data that is included in the network request when the request is a PING (as opposed to GET/POST). It might be a bug or intentional, no way for me to know. Thus, we only see that a request was made and none of the parameters are included, so we fallback to default type (Page View).

**Comment by MisterPhilip** [comment]
I'll be closing this one since https://github.com/MisterPhilip/omnibug/issues/213 is the main issue and I'm trying to clean up the issues. Once that one is resolved this will be resolved too.
