### ISSUE TITLE
Omnibug doesn,t support last version of Chrome

### ISSUE THREAD

**Issue by Stoyan-86** [MisterPhilip/omnibug#231]
**Describe the bug**
Omnibug doesn,t support last version of Chrome Version 116.0.5845.97 (Official Build) (64-bit)

**Desktop :**
 - OS: [Windows 10 Enterprise 64bi]
 - Browser [Chrome]
 - Version [Version 116.0.5845.97 (Official Build) (64-bit)]
 - Omnibug Version [e.g. 1.6.0]

**Comment by Stoyan-86** [comment]
No errors appear, but the Omnibug tab is not visible.
I tried removing the extension and adding it again, but to no success. 
I want to note that what I show in the video before worked.

https://github.com/MisterPhilip/omnibug/assets/76531188/61935a16-35f9-48b9-ba6d-b43d09e7d77f

**Comment by MisterPhilip** [comment]
Yeah, this looks related to #219; no developer tool extensions will load on `file://` URIs either. Unpacked extensions seem to work OK, but published ones do not. 

I'm afraid until Google/Chromium changes this, the only workaround is to use a local web server to serve your html/assets instead of going to the `file://` URI.

**Comment by Stoyan-86** [comment]
@MisterPhilip many thanks for your time and help!

**Comment by MisterPhilip** [comment]
Closing this since it is related to #219 - will keep that one open!
