### ISSUE TITLE
Adobe Experience Platform WebSDK: Events not seen where  'Document will unload' feature enabled

### ISSUE THREAD

**Issue by dan-l1** [MisterPhilip/omnibug#254]
Hi

Within the Adobe Experience Platform WebSDK extension, you are able to select an option that will fire an event if the user is navigating from the page, this is via the 'Document will unload' checkbox within the 'Send event' action type.

Within the network tab you can see these types of calls being fired with a '204 No Content' status.

Although within Omnibug I can see these calls being fired, the Events are not shown.  This means for these types of calls I'm having to use the Assurance tool, which is nowhere near nice to use as Omnibug, or go into the network calls itself, which is very time consuming.

What I would like is for Omnibug to display the events of these types of calls

Many thanks

Dan

![image](https://github.com/MisterPhilip/omnibug/assets/147704147/df7308ec-42aa-4da2-8784-5a7104c76539)
![image](https://github.com/MisterPhilip/omnibug/assets/147704147/0c4fdd90-73fa-420b-872a-cf596acd14b6)
![image](https://github.com/MisterPhilip/omnibug/assets/147704147/49590bfa-047a-451d-b3d1-8e8f9994f47c)
![image](https://github.com/MisterPhilip/omnibug/assets/147704147/03038b2e-7eb9-4ae6-90c2-e7a8d890db57)

**Comment by MisterPhilip** [comment]
Huh, interesting - I didn't realize the events weren't being shown for this link type. I will take a look!

**Comment by dan-l1** [comment]
Thank you, if this could be fixed it would save hours of time and frustration!

**Comment by MisterPhilip** [comment]
Sorry it took so long to dig into, life has been hectic. Unfortunately, this looks like it is a Chrome bug that I have no control over. I'm investigating other ways of capturing the network requests so that I can capture this data, but until then this data is not exposed to Omnibug.

I have added a warning that lets users know that more data may be sent than is shown in Omnibug. 

I'll be closing this one since #213 is the main issue. Once that one is resolved this will be resolved too.
