### ISSUE TITLE
Event tracked twice in chrome onminbug extension

### ISSUE THREAD

**Issue by shailender-rajput** [MisterPhilip/omnibug#43]
I am facing an issue with omnibug extension in chrome, It tracks a click/load event twice with Google/Universal Analytics.

But omnibug in firefox tracks the event only once, which is the correct scenario.
Is this a known bug in omnibug?
Kindly reply asap

Thanks

**Comment by MisterPhilip** [comment]
It is not. Are the network requests possibly returning a 3XX status? E.g. a 302 or 307 redirect to the https version?

**Comment by shailender-rajput** [comment]
Yes there are two requests one gives 302 status and other one 
you can see in the screenshot attached

<img width="1394" alt="omnibug" src="https://cloud.githubusercontent.com/assets/12758847/25420521/1a6e60ba-2a76-11e7-9546-a7cedf9e6da1.png">
gives 307

**Comment by martijnschoenmakers** [comment]
Today I also received a question from a client asking about the double hits she found in OmniBug for Adobe Analytics. The reason here was also due to a 3XX status code. I understand why this is seen by OmniBug, but I think the question is if this is desired. Maybe this is useful for some providers, but I see a lot of customers using OmniBug to see what data is being send to Adobe Analytics and for such showing the 302 is misleading them.

A easy solution might be to use some clear (color) coding for redirects?

**Comment by FranciscoG** [comment]
This is happening with me as well.

**Comment by MisterPhilip** [comment]
The latest version in Chrome now allows you to see when a redirect happens (and the ability to hide them). Firefox support is coming soon, but I'm closing this for now since it's updated in the code base.
